src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Form/CreateAddressType.php
<?php

namespace BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Form;

use BlockCypher\AppWallet\App\Command\CreateAddressCommand;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CreateAddressType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // TODO: use select for accountId

        $builder
            ->add('accountId', 'text')
            ->add('tag', 'text', array('required' => false))
            ->add('callbackUrl', 'text', array('required' => false));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BlockCypher\AppWallet\App\Command\CreateAddressCommand',
            'empty_data' => function (FormInterface $form) {
                $createAddressCommand = new CreateAddressCommand(
                    $form->get('accountId')->getData(),
                    $form->get('tag')->getData(),
                    $form->get('callbackUrl')->getData()
                );
                return $createAddressCommand;
            }
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'bc_app_wallet_address_create_address';
    }
}

src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Controller/Wallet/Addresses.php
<?php

namespace BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Wallet;

use BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\AppWalletController;
use BlockCypher\AppWallet\Presentation\Facade\WalletServiceFacade;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Translation\TranslatorInterface;

class Addresses extends AppWalletController
{
    /**
     * @var WalletServiceFacade
     */
    private $walletServiceFacade;

    /**
     * @param EngineInterface $templating
     * @param TranslatorInterface $translator
     * @param WalletServiceFacade $walletServiceFacade
     */
    public function __construct(
        EngineInterface $templating,
        TranslatorInterface $translator,
        WalletServiceFacade $walletServiceFacade)
    {
        parent::__construct($templating, $translator);
        $this->walletServiceFacade = $walletServiceFacade;
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function __invoke(Request $request)
    {
        $walletId = $request->get('walletId');

        $addresses = $this->walletServiceFacade->listWalletAddresses($walletId);

        // DEBUG
        //var_dump($addresses);
        //die();

        $template = $this->getBaseTemplatePrefix() . ':Address:index.html';

        // TODO
        $currentPage = 1;
        $maxPages = 0; // get_max_pages(num_items=address_details['final_n_tx'], items_per_page=TXNS_PER_PAGE),

        return $this->templating->renderResponse(
            $template . '.' . $this->getEngine(),
            array(
                // TODO: move to base controller and merge arrays
                'is_home' => false,
                'user' => array('is_authenticated' => true),
                'messages' => array(),
                //
                'coin_symbol' => 'btc',
                'current_page' => $currentPage,
                'max_pages' => $maxPages,
                'wallet_id' => $walletId,
                'num_all_addresses' => count($addresses),
                'addresses' => $addresses
            )
        );
    }
}

src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Controller/Wallet/Create.php
<?php

namespace BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Wallet;

use BlockCypher\AppWallet\App\Command\CreateWalletCommand;
use BlockCypher\AppWallet\App\Command\CreateWalletCommandValidator;
use BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\AppWalletController;
use BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Form\Wallet\WalletFormFactory;
use SimpleBus\Message\Bus\MessageBus;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Translation\TranslatorInterface;

class Create extends AppWalletController
{
    /**
     * @var RouterInterface
     */
    private $router;

    /**
     * @var WalletFormFactory
     */
    private $walletFormFactory;

    /**
     * @var MessageBus
     */
    private $commandBus;

    /**
     * @param TokenStorageInterface $tokenStorage
     * @param EngineInterface $templating
     * @param TranslatorInterface $translator
     * @param Session $session
     * @param RouterInterface $router
     * @param WalletFormFactory $walletFormFactory
     * @param MessageBus $commandBus
     */
    public function __construct(
        TokenStorageInterface $tokenStorage,
        EngineInterface $templating,
        TranslatorInterface $translator,
        Session $session,
        RouterInterface $router,
        WalletFormFactory $walletFormFactory,
        MessageBus $commandBus)
    {
        parent::__construct($tokenStorage, $templating, $translator, $session);
        $this->router = $router;
        $this->walletFormFactory = $walletFormFactory;
        $this->commandBus = $commandBus;
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function __invoke(Request $request)
    {
        $user = $this->getUser();

        if (!$user) {
            throw $this->createAccessDeniedException();
        }

        $createWalletCommand = $this->createCreateWalletCommand();

        $createWalletForm = $this->walletFormFactory->createCreateForm($createWalletCommand);

        $createWalletForm->handleRequest($request);

        if (!$createWalletForm->isValid()) {

            $validationMsg = $this->getAllFormErrorMessagesAsString($createWalletForm);
            $this->addFlash('error', $this->trans('create_transaction_form.flash.invalid_form') . ' ' . $validationMsg);

        } else {

            /** @var CreateWalletCommand $createWalletCommand */
            $createWalletCommand = $createWalletForm->getData();

            $createWalletCommand->setWalletOwnerId($user->getId()->getValue());
            $createWalletCommand->setToken($user->getBlockCypherToken());

            try {

                $commandValidator = new CreateWalletCommandValidator();
                $commandValidator->validate($createWalletCommand);

                $this->commandBus->handle($createWalletCommand);

                $this->addFlash('success', $this->trans('wallet.flash.create_successfully'));

                $url = $this->router->generate('bc_app_wallet_wallet.index');

                return new RedirectResponse($url);

            } catch (\Exception $e) {
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->renderWalletShowNew($request, $createWalletForm->createView());
    }

    /**
     * @param Request $request
     * @param FormView $createWalletFormView
     * @return Response
     */
    private function renderWalletShowNew(
        Request $request,
        FormView $createWalletFormView
    )
    {
        $template = $this->getBaseTemplatePrefix() . ':Wallet:show_new.html';

        return $this->templating->renderResponse(
            $template . '.' . $this->getEngine(),
            array_merge($this->getBasicTemplateVariables($request),
                array(
                    'wallet_form' => $createWalletFormView
                )
            )
        );
    }
}

src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Controller/Wallet/Index.php
<?php

namespace BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Wallet;

use BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\AppWalletController;
use BlockCypher\AppWallet\Presentation\Facade\WalletServiceFacade;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Translation\TranslatorInterface;

class Index extends AppWalletController
{
    /**
     * @var WalletServiceFacade
     */
    private $walletServiceFacade;

    /**
     * @param TokenStorageInterface $tokenStorage
     * @param EngineInterface $templating
     * @param TranslatorInterface $translator
     * @param Session $session
     * @param WalletServiceFacade $walletServiceFacade
     */
    public function __construct(
        TokenStorageInterface $tokenStorage,
        EngineInterface $templating,
        TranslatorInterface $translator,
        Session $session,
        WalletServiceFacade $walletServiceFacade)
    {
        parent::__construct($tokenStorage, $templating, $translator, $session);
        $this->walletServiceFacade = $walletServiceFacade;
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function __invoke(Request $request)
    {
        $user = $this->getUser();

        //$token = $this->tokenStorage->getToken();
        //var_dump($token);
        //die();

        if (!$user) {
            throw $this->createAccessDeniedException();
        }

        $walletListItemDtos = $this->walletServiceFacade->listWalletsOfUserId($user->getId()->getValue());

        $template = $this->getBaseTemplatePrefix() . ':Wallet:index.html';

        // TODO: paging
        $currentPage = 1;
        $maxPages = 0; // get_max_pages(num_items=address_details['final_n_tx'], items_per_page=TXNS_PER_PAGE),

        return $this->templating->renderResponse(
            $template . '.' . $this->getEngine(),
            array_merge($this->getBasicTemplateVariables($request),
                array(
                    'current_page' => $currentPage,
                    'max_pages' => $maxPages,
                    'num_all_wallets' => count($walletListItemDtos),
                    'wallets' => $walletListItemDtos,
                )
            )
        );
    }
}

src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Controller/Wallet/ShowNew.php
<?php

namespace BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Wallet;

use BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\AppWalletController;
use BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Form\Wallet\WalletFormFactory;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Translation\TranslatorInterface;

class ShowNew extends AppWalletController
{
    /**
     * @var WalletFormFactory
     */
    private $walletFormFactory;

    /**
     * @param TokenStorageInterface $tokenStorage
     * @param EngineInterface $templating
     * @param TranslatorInterface $translator
     * @param Session $session
     * @param WalletFormFactory $walletFormFactory
     */
    public function __construct(
        TokenStorageInterface $tokenStorage,
        EngineInterface $templating,
        TranslatorInterface $translator,
        Session $session,
        WalletFormFactory $walletFormFactory)
    {
        parent::__construct($tokenStorage, $templating, $translator, $session);
        $this->walletFormFactory = $walletFormFactory;
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function __invoke(Request $request)
    {
        $user = $this->getUser();

        if (!$user) {
            throw $this->createAccessDeniedException();
        }

        $createWalletCommand = $this->createCreateWalletCommand();

        $createWalletForm = $this->walletFormFactory->createCreateForm($createWalletCommand);

        $template = $this->getBaseTemplatePrefix() . ':Wallet:show_new.html';

        return $this->templating->renderResponse(
            $template . '.' . $this->getEngine(),
            array_merge($this->getBasicTemplateVariables($request),
                array(
                    'wallet_form' => $createWalletForm->createView(),
                )
            )
        );
    }
}

src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Controller/Wallet/Transactions.php
<?php

namespace BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Wallet;

use BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\AppWalletController;
use BlockCypher\AppWallet\Presentation\Facade\WalletServiceFacade;
use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Translation\TranslatorInterface;

class Transactions extends AppWalletController
{
    /**
     * @var WalletServiceFacade
     */
    private $walletServiceFacade;

    /**
     * @param EngineInterface $templating
     * @param TranslatorInterface $translator
     * @param WalletServiceFacade $walletServiceFacade
     */
    public function __construct(
        EngineInterface $templating,
        TranslatorInterface $translator,
        WalletServiceFacade $walletServiceFacade)
    {
        parent::__construct($templating, $translator);
        $this->walletServiceFacade = $walletServiceFacade;
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function __invoke(Request $request)
    {
        $walletId = $request->get('walletId');

        $walletTransactionsDto = $this->walletServiceFacade->listWalletTransactions($walletId);

        $transactions = $walletTransactionsDto->getTransactionListItemDtos();

        $template = $this->getBaseTemplatePrefix() . ':Wallet:transactions.html';

        // DEBUG
        //var_dump($wallets);
        //die();

        // TODO
        $currentPage = 1;
        $maxPages = 0; // get_max_pages(num_items=address_details['final_n_tx'], items_per_page=TXNS_PER_PAGE),

        $BLOCKCYPHER_PUBLIC_KEY = "c0afcccdde5081d6429de37d16166ead";

        return $this->templating->renderResponse(
            $template . '.' . $this->getEngine(),
            array(
                // TODO: move to base controller and merge arrays
                'is_home' => false,
                'user' => array('is_authenticated' => true),
                'messages' => array(),
                //
                'coin_symbol' => 'btc',
                'current_page' => $currentPage,
                'num_all_wallets' => count($transactions),
                'max_pages' => $maxPages,
                'wallet_id' => $walletId,
                'total_sent_satoshis' => $walletTransactionsDto->getTotalSent(),
                'total_received_satoshis' => $walletTransactionsDto->getTotalReceived(),
                'total_balance_satoshis' => $walletTransactionsDto->getFinalBalance(),
                'unconfirmed_balance_satoshis' => $walletTransactionsDto->getUnconfirmedBalance(),
                'num_all_txns' => $walletTransactionsDto->getNTx(),
                'num_unconfirmed_txns' => $walletTransactionsDto->getUnconfirmedBalance(),
                'all_transactions' => $transactions,
                'BLOCKCYPHER_PUBLIC_KEY' => $BLOCKCYPHER_PUBLIC_KEY
            )
        );
    }
}

//array(
//    // TODO: move to base controller and merge arrays
//    'is_home' => false,
//    'user' => array('is_authenticated' => true),
//    'messages' => array(),
//    //
//    'coin_symbol' => $coinSymbol,
//    'address' => $address,
//    'api_url' => $apiUrl,
//    'wallet_name' => $walletName,
//    'current_page' => $currentPage,
//    'max_pages' => $maxPages,
//    'total_sent_satoshis' => $addressDetailsArray['total_sent'],
//    'total_received_satoshis' => $addressDetailsArray['total_received'],
//    'unconfirmed_balance_satoshis' => $addressDetailsArray['unconfirmed_balance'],
//    'confirmed_balance_satoshis' => $addressDetailsArray['balance'],
//    'total_balance_satoshis' => $addressDetailsArray['final_balance'],
//    'all_transactions' => $allTransactions,
//    'num_confirmed_txns' => $addressDetailsArray['n_tx'],
//    'num_unconfirmed_txns' => $addressDetailsArray['unconfirmed_n_tx'],
//    'num_all_txns' => $addressDetailsArray['final_n_tx'],
//    'BLOCKCYPHER_PUBLIC_KEY' => $BLOCKCYPHER_PUBLIC_KEY,
//)

src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Resources/views/Wallet/index.html.twig
{% extends "BlockCypherAppCommonInfrastructureLayoutBundle::base.html.twig" %}

{% block title %}Wallets{% endblock title %}

{% block page_header %}
    <h1>
        <i class="fa fa-qrcode"></i>
        Wallets
    </h1>

    <h2 class="tagline wrapit semi">
        Your wallets
    </h2>
{% endblock page_header %}

{% block content %}
    <div class="container">

        <div class="section">
            <div class="col-md-12">
                <p class="text-center">
                    <a href="{{ path('bc_app_wallet_wallet.index') }}"
                       class="btn btn-lg btn-default">
                        <i class="fa fa-bank"></i>
                        Wallets
                    </a>
                    <a href="{{ path('bc_app_wallet_wallet.new') }}"
                       class="btn btn-lg btn-default">
                        <i class="fa fa-plus"></i>
                        New Wallet
                    </a>
                    <a href="{{ path('bc_app_wallet_faucet.show') }}"
                       class="btn btn-lg btn-default">
                        <i class="fa fa-money"></i>
                        Faucet
                    </a>
                </p>
            </div>
        </div>

        <div class="col-md-12">
            {% include "BlockCypherAppWalletInfrastructureAppWalletBundle:Modules:messages.html.twig" %}
        </div>

        <div class="col-md-12">
            {% include "BlockCypherAppWalletInfrastructureAppWalletBundle:Modules:flash_messages.html.twig" %}
        </div>

        {% if wallets %}

            <div class="col-md-12">

                <h2>
                    {{ num_all_wallets|intcomma }} Wallets
                </h2>

                {% if max_pages > 1 %}
                    <div class="section pager">
                        <div class="row">
                            <div class="col-sm-4 text-left">
                                {% if current_page > 1 %}
                                    <a href="?page={{ current_page|add(-1)|intcomma }}" class="btn btn-default">
                                        <i class="fa fa-angle-double-left"></i>
                                        Previous Page
                                    </a>
                                {% endif %}
                            </div>

                            <div class="col-sm-4 text-center">
                                Page of
                            </div>

                            <div class="col-sm-4 text-right">
                                {% if current_page < max_pages %}
                                    <a href="?page={{ current_page|add(1)|intcomma }}" class="btn btn-default">
                                        Next Page
                                        <i class="fa fa-angle-double-right"></i>
                                    </a>
                                {% endif %}
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                {% endif %}

                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th>Name</th>
                            <th>Final Balance</th>
                            <th>Coin Symbol</th>
                            <th>Creation Time</th>
                            <th>Id</th>
                            <th>Actions</th>
                            <th>API</th>
                        </tr>
                        {% for wallet in wallets %}
                            <tr class="tx-row" id="{{ wallet.id }}">
                                <td class="">
                                    {{ wallet.name }}
                                </td>
                                <td class="">
                                    {# {{ wallet.balance|satoshis_to_btc_rounding|intcomma }}&nbsp;{{ wallet.type|coin_symbol_to_currency_name }} #}
                                    {{ wallet.balance|satoshis_to_btc_full|intcomma(8) }}
                                    &nbsp;{{ wallet.coinSymbol|coin_symbol_to_currency_name }} {# without rounding #}
                                </td>
                                <td class="">
                                    {{ wallet.coinSymbol }}
                                </td>
                                <td>
                                    <time class="timeago"
                                          datetime="{{ wallet.creationTime|date('Y-m-d\TH:i:s') }}Z">
                                        {{ wallet.creationTime|date('Y-m-d H:i') }} GMT
                                    </time>
                                </td>
                                <td class="truncate">
                                    <a href="{{ path('bc_app_wallet_transaction.index', {'walletId': wallet.id }) }}"
                                       class="hidden-xs tx-list small">
                                        {{ wallet.id }}
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ path('bc_app_wallet_address.index', {'walletId': wallet.id }) }}"
                                       class="hidden-xs tx-list small">[Addresses]</a>
                                    <a href="{{ path('bc_app_wallet_transaction.index', {'walletId': wallet.id }) }}"
                                       class="hidden-xs tx-list small">[History]</a>
                                    <a href="{{ path('bc_app_wallet_transaction.new', {'walletId': wallet.id }) }}"
                                       class="hidden-xs tx-list small">[Send Funds]</a>
                                </td>
                                <td><a target="_blank" href="{{ wallet.apiUrl }}"><i
                                                class="fa fa-external-link"></i></a></td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>

                {% if max_pages > 1 %}
                    <div class="section pager">
                        <div class="row">
                            <div class="col-sm-4 text-left">
                                {% if current_page > 1 %}
                                    <a href="?page={{ current_page|add(-1)|intcomma }}" class="btn btn-default">
                                        <i class="fa fa-angle-double-left"></i>
                                        Previous Page
                                    </a>
                                {% endif %}
                            </div>

                            <div class="col-sm-4 text-center">
                                Page of
                            </div>

                            <div class="col-sm-4 text-right">
                                {% if current_page < max_pages %}
                                    <a href="?page={{ current_page|add(1)|intcomma }}" class="btn btn-default">
                                        Next Page
                                        <i class="fa fa-angle-double-right"></i>
                                    </a>
                                {% endif %}
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                {% endif %}

            </div>

        {% else %}
            <p>No wallets detected.
                <small>This account does not contain any wallet. Check that you have logged in with the right token.
                </small>
            </p>
        {% endif %}

    </div>

{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Resources/views/Wallet/show_new.html.twig
{% extends "BlockCypherAppCommonInfrastructureLayoutBundle::base.html.twig" %}

{% block title %}Addresses{% endblock title %}

{% block page_header %}
    <h1>
        <i class="fa fa-qrcode"></i>
        Create New Wallet
    </h1>

    <h2 class="tagline wrapit semi">
    </h2>
{% endblock page_header %}

{% block content %}
    <div class="container">

        <div class="section">
            <div class="col-md-12">
                <p class="text-center">
                    <a href="{{ path('bc_app_wallet_wallet.index') }}"
                       class="btn btn-lg btn-default">
                        <i class="fa fa-bank"></i>
                        Wallets
                    </a>
                    <a href="{{ path('bc_app_wallet_wallet.new') }}"
                       class="btn btn-lg btn-default">
                        <i class="fa fa-plus"></i>
                        New Wallet
                    </a>
                </p>
            </div>
        </div>

        <div class="col-md-12">
            {% include "BlockCypherAppWalletInfrastructureAppWalletBundle:Modules:messages.html.twig" %}
        </div>

        <div class="col-md-12">
            {% include "BlockCypherAppWalletInfrastructureAppWalletBundle:Modules:flash_messages.html.twig" %}
        </div>

        <div class="col-md-12">

            <h2></h2>

            {#{{ form_start(wallet_form) }}
            {{ form_widget(wallet_form) }}
            {{ form_end(wallet_form) }}#}

            <div class="form-well">

                {{ form_start(wallet_form, {'attr': {'class': 'form-horizontal'}}) }}
                {{ form_errors(wallet_form) }}
                <div class="form-group">
                    <label for="type" class="col-sm-2 control-label">Coin</label>

                    <div class="col-sm-10">
                        {{ form_widget(wallet_form.coinSymbol, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="tag" class="col-sm-2 control-label">Wallet Name</label>

                    <div class="col-sm-10">
                        {{ form_widget(wallet_form.name, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Create Wallet</button>
                    <p class="help-block">
                        <small>This action uses this BlockCypher API endpoint:<a
                                    href="http://dev.blockcypher.com/#wallet_api">/v1/{coinSymbol}/{chain}/wallets</a>
                            POST
                        </small>
                    </p>
                </div>
                {{ form_end(wallet_form) }}

            </div>

        </div>
    </div>

{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}